language: python
python:
  - "3.6"
# command to install dependencies
before_script:
  - easy_install distribute
  - pip install -r requirements.txt
# command to run script 
script:
  - python algo.py preferences.csv
